### ISSUE TITLE
python3.4 环境无法运行，缺失文件

### ISSUE THREAD

**Issue by mysefs** [changye/AutoTrade#1]
Traceback (most recent call last):
  File "d:\work\python\AutoTrade\test.py", line 6, in <module>
    from Trade.Trader import *
  File "d:\work\python\AutoTrade\Trade\Trader.py", line 1, in <module>
    from Socket.GFSocket import GFSocket
  File "d:\work\python\AutoTrade\Socket\GFSocket.py", line 1, in <module>
    from Socket.Socket import Socket
ImportError: No module named 'Socket.Socket'

**Comment by changye** [comment]
已修复。
